/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Note {
    id: bigint;
    title: string;
    content: string;
    createdAt: bigint;
    updatedAt: bigint;
}
export interface StudentData {
    examResults: Array<ExamResult>;
    progress: ProgressData;
    notes: Array<Note>;
    dailyPlans: Array<DailyPlan>;
    profile: StudentProfile;
}
export interface Sound {
    file: ExternalBlob;
    category: SoundCategory;
    uploadedAt: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface AudioFile {
    id: bigint;
    audioLabel: string;
    file: ExternalBlob;
    uploadedAt: bigint;
}
export interface ProgressData {
    progressPercentage: bigint;
    lastActivityDate: bigint;
    totalScore: bigint;
    completedActivities: Array<string>;
    achievementBadge: string;
}
export interface StudentProfile {
    username: string;
    createdAt: bigint;
    lastUpdated: bigint;
    soundEnabled: boolean;
    studentNumber: string;
    notificationEnabled: boolean;
    avatar: string;
}
export interface AudioFileList {
    audioFiles: Array<AudioFileNoFile>;
}
export interface AdminProfile {
    name: string;
}
export interface ExamResult {
    id: bigint;
    completedAt: bigint;
    date: string;
    score: bigint;
    totalQuestions: bigint;
    educationLevel: string;
}
export interface DailyPlan {
    id: bigint;
    date: string;
    createdAt: bigint;
    activities: Array<string>;
    updatedAt: bigint;
    goals: Array<string>;
}
export interface AudioFileNoFile {
    id: bigint;
    audioLabel: string;
    uploadedAt: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum SoundCategory {
    anlaticiBolumGecisi = "anlaticiBolumGecisi",
    anlaticiGorevBaslangici = "anlaticiGorevBaslangici",
    arkaPlanMuzigi = "arkaPlanMuzigi",
    basari = "basari",
    yanlisCevap = "yanlisCevap",
    anlaticiMotivasyon = "anlaticiMotivasyon",
    secim = "secim",
    anlaticiHataTekrarDene = "anlaticiHataTekrarDene",
    anlaticiHosgeldiniz = "anlaticiHosgeldiniz",
    anlaticiBasari = "anlaticiBasari",
    uyari = "uyari",
    dogruCevap = "dogruCevap",
    gecisSesi = "gecisSesi"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    canUploadContent(): Promise<boolean>;
    deleteAudio(id: bigint): Promise<void>;
    deleteDailyPlan(studentNumber: string, planId: bigint): Promise<void>;
    deleteNote(studentNumber: string, noteId: bigint): Promise<void>;
    deleteStudentProfile(studentNumber: string): Promise<void>;
    getAudioFile(id: bigint): Promise<AudioFile | null>;
    getCallerUserProfile(): Promise<AdminProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDailyPlans(studentNumber: string): Promise<Array<DailyPlan>>;
    getExamResults(studentNumber: string): Promise<Array<ExamResult>>;
    getNotes(studentNumber: string): Promise<Array<Note>>;
    getProgress(studentNumber: string): Promise<ProgressData | null>;
    getSound(category: SoundCategory): Promise<Sound | null>;
    getStudentData(studentNumber: string): Promise<StudentData | null>;
    getStudentProfile(studentNumber: string): Promise<StudentProfile | null>;
    getUserProfile(user: Principal): Promise<AdminProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listAllAudioFilesWithFiles(): Promise<Array<AudioFile>>;
    listAudioFiles(): Promise<AudioFileList>;
    listSounds(): Promise<Array<Sound>>;
    saveCallerUserProfile(profile: AdminProfile): Promise<void>;
    saveDailyPlan(studentNumber: string, plan: DailyPlan): Promise<bigint>;
    saveExamResult(studentNumber: string, exam: ExamResult): Promise<bigint>;
    saveNote(studentNumber: string, note: Note): Promise<bigint>;
    saveProgress(studentNumber: string, progress: ProgressData): Promise<void>;
    saveStudentProfile(profile: StudentProfile): Promise<void>;
    syncStudentData(studentNumber: string, data: StudentData): Promise<void>;
    updateDailyPlan(studentNumber: string, planId: bigint, updatedPlan: DailyPlan): Promise<void>;
    updateNote(studentNumber: string, noteId: bigint, updatedNote: Note): Promise<void>;
    uploadAudio(audioLabel: string, blob: ExternalBlob): Promise<bigint>;
    uploadSound(category: SoundCategory, fileOrUrl: {
        __kind__: "url";
        url: string;
    } | {
        __kind__: "file";
        file: ExternalBlob;
    }): Promise<string>;
}
import type { AdminProfile as _AdminProfile, AudioFile as _AudioFile, ExternalBlob as _ExternalBlob, ProgressData as _ProgressData, Sound as _Sound, SoundCategory as _SoundCategory, StudentData as _StudentData, StudentProfile as _StudentProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async canUploadContent(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.canUploadContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.canUploadContent();
            return result;
        }
    }
    async deleteAudio(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAudio(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAudio(arg0);
            return result;
        }
    }
    async deleteDailyPlan(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDailyPlan(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDailyPlan(arg0, arg1);
            return result;
        }
    }
    async deleteNote(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0, arg1);
            return result;
        }
    }
    async deleteStudentProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudentProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudentProfile(arg0);
            return result;
        }
    }
    async getAudioFile(arg0: bigint): Promise<AudioFile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAudioFile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAudioFile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<AdminProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyPlans(arg0: string): Promise<Array<DailyPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyPlans(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyPlans(arg0);
            return result;
        }
    }
    async getExamResults(arg0: string): Promise<Array<ExamResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExamResults(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExamResults(arg0);
            return result;
        }
    }
    async getNotes(arg0: string): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotes(arg0);
            return result;
        }
    }
    async getProgress(arg0: string): Promise<ProgressData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgress(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgress(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSound(arg0: SoundCategory): Promise<Sound | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSound(to_candid_SoundCategory_n18(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSound(to_candid_SoundCategory_n18(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentData(arg0: string): Promise<StudentData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentData(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentData(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentProfile(arg0: string): Promise<StudentProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentProfile(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentProfile(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<AdminProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllAudioFilesWithFiles(): Promise<Array<AudioFile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllAudioFilesWithFiles();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllAudioFilesWithFiles();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAudioFiles(): Promise<AudioFileList> {
        if (this.processError) {
            try {
                const result = await this.actor.listAudioFiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAudioFiles();
            return result;
        }
    }
    async listSounds(): Promise<Array<Sound>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSounds();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSounds();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: AdminProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveDailyPlan(arg0: string, arg1: DailyPlan): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDailyPlan(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDailyPlan(arg0, arg1);
            return result;
        }
    }
    async saveExamResult(arg0: string, arg1: ExamResult): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveExamResult(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveExamResult(arg0, arg1);
            return result;
        }
    }
    async saveNote(arg0: string, arg1: Note): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveNote(arg0, arg1);
            return result;
        }
    }
    async saveProgress(arg0: string, arg1: ProgressData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProgress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProgress(arg0, arg1);
            return result;
        }
    }
    async saveStudentProfile(arg0: StudentProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveStudentProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveStudentProfile(arg0);
            return result;
        }
    }
    async syncStudentData(arg0: string, arg1: StudentData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.syncStudentData(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.syncStudentData(arg0, arg1);
            return result;
        }
    }
    async updateDailyPlan(arg0: string, arg1: bigint, arg2: DailyPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDailyPlan(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDailyPlan(arg0, arg1, arg2);
            return result;
        }
    }
    async updateNote(arg0: string, arg1: bigint, arg2: Note): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNote(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNote(arg0, arg1, arg2);
            return result;
        }
    }
    async uploadAudio(arg0: string, arg1: ExternalBlob): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadAudio(arg0, await to_candid_ExternalBlob_n29(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadAudio(arg0, await to_candid_ExternalBlob_n29(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadSound(arg0: SoundCategory, arg1: {
        __kind__: "url";
        url: string;
    } | {
        __kind__: "file";
        file: ExternalBlob;
    }): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadSound(to_candid_SoundCategory_n18(this._uploadFile, this._downloadFile, arg0), await to_candid_variant_n30(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadSound(to_candid_SoundCategory_n18(this._uploadFile, this._downloadFile, arg0), await to_candid_variant_n30(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_AudioFile_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AudioFile): Promise<AudioFile> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_SoundCategory_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SoundCategory): SoundCategory {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_Sound_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sound): Promise<Sound> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AudioFile]): Promise<AudioFile | null> {
    return value.length === 0 ? null : await from_candid_AudioFile_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdminProfile]): AdminProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProgressData]): ProgressData | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Sound]): Promise<Sound | null> {
    return value.length === 0 ? null : await from_candid_Sound_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentData]): StudentData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentProfile]): StudentProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    audioLabel: string;
    file: _ExternalBlob;
    uploadedAt: bigint;
}): Promise<{
    id: bigint;
    audioLabel: string;
    file: ExternalBlob;
    uploadedAt: bigint;
}> {
    return {
        id: value.id,
        audioLabel: value.audioLabel,
        file: await from_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.file),
        uploadedAt: value.uploadedAt
    };
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    file: _ExternalBlob;
    category: _SoundCategory;
    uploadedAt: bigint;
}): Promise<{
    file: ExternalBlob;
    category: SoundCategory;
    uploadedAt: bigint;
}> {
    return {
        file: await from_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.file),
        category: from_candid_SoundCategory_n23(_uploadFile, _downloadFile, value.category),
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    anlaticiBolumGecisi: null;
} | {
    anlaticiGorevBaslangici: null;
} | {
    arkaPlanMuzigi: null;
} | {
    basari: null;
} | {
    yanlisCevap: null;
} | {
    anlaticiMotivasyon: null;
} | {
    secim: null;
} | {
    anlaticiHataTekrarDene: null;
} | {
    anlaticiHosgeldiniz: null;
} | {
    anlaticiBasari: null;
} | {
    uyari: null;
} | {
    dogruCevap: null;
} | {
    gecisSesi: null;
}): SoundCategory {
    return "anlaticiBolumGecisi" in value ? SoundCategory.anlaticiBolumGecisi : "anlaticiGorevBaslangici" in value ? SoundCategory.anlaticiGorevBaslangici : "arkaPlanMuzigi" in value ? SoundCategory.arkaPlanMuzigi : "basari" in value ? SoundCategory.basari : "yanlisCevap" in value ? SoundCategory.yanlisCevap : "anlaticiMotivasyon" in value ? SoundCategory.anlaticiMotivasyon : "secim" in value ? SoundCategory.secim : "anlaticiHataTekrarDene" in value ? SoundCategory.anlaticiHataTekrarDene : "anlaticiHosgeldiniz" in value ? SoundCategory.anlaticiHosgeldiniz : "anlaticiBasari" in value ? SoundCategory.anlaticiBasari : "uyari" in value ? SoundCategory.uyari : "dogruCevap" in value ? SoundCategory.dogruCevap : "gecisSesi" in value ? SoundCategory.gecisSesi : value;
}
async function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AudioFile>): Promise<Array<AudioFile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_AudioFile_n11(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Sound>): Promise<Array<Sound>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Sound_n21(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_SoundCategory_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SoundCategory): _SoundCategory {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SoundCategory): {
    anlaticiBolumGecisi: null;
} | {
    anlaticiGorevBaslangici: null;
} | {
    arkaPlanMuzigi: null;
} | {
    basari: null;
} | {
    yanlisCevap: null;
} | {
    anlaticiMotivasyon: null;
} | {
    secim: null;
} | {
    anlaticiHataTekrarDene: null;
} | {
    anlaticiHosgeldiniz: null;
} | {
    anlaticiBasari: null;
} | {
    uyari: null;
} | {
    dogruCevap: null;
} | {
    gecisSesi: null;
} {
    return value == SoundCategory.anlaticiBolumGecisi ? {
        anlaticiBolumGecisi: null
    } : value == SoundCategory.anlaticiGorevBaslangici ? {
        anlaticiGorevBaslangici: null
    } : value == SoundCategory.arkaPlanMuzigi ? {
        arkaPlanMuzigi: null
    } : value == SoundCategory.basari ? {
        basari: null
    } : value == SoundCategory.yanlisCevap ? {
        yanlisCevap: null
    } : value == SoundCategory.anlaticiMotivasyon ? {
        anlaticiMotivasyon: null
    } : value == SoundCategory.secim ? {
        secim: null
    } : value == SoundCategory.anlaticiHataTekrarDene ? {
        anlaticiHataTekrarDene: null
    } : value == SoundCategory.anlaticiHosgeldiniz ? {
        anlaticiHosgeldiniz: null
    } : value == SoundCategory.anlaticiBasari ? {
        anlaticiBasari: null
    } : value == SoundCategory.uyari ? {
        uyari: null
    } : value == SoundCategory.dogruCevap ? {
        dogruCevap: null
    } : value == SoundCategory.gecisSesi ? {
        gecisSesi: null
    } : value;
}
async function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "url";
    url: string;
} | {
    __kind__: "file";
    file: ExternalBlob;
}): Promise<{
    url: string;
} | {
    file: _ExternalBlob;
}> {
    return value.__kind__ === "url" ? {
        url: value.url
    } : value.__kind__ === "file" ? {
        file: await to_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value.file)
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
