/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminProfile { 'name' : string }
export interface AudioFile {
  'id' : bigint,
  'audioLabel' : string,
  'file' : ExternalBlob,
  'uploadedAt' : bigint,
}
export interface AudioFileList { 'audioFiles' : Array<AudioFileNoFile> }
export interface AudioFileNoFile {
  'id' : bigint,
  'audioLabel' : string,
  'uploadedAt' : bigint,
}
export interface DailyPlan {
  'id' : bigint,
  'date' : string,
  'createdAt' : bigint,
  'activities' : Array<string>,
  'updatedAt' : bigint,
  'goals' : Array<string>,
}
export interface ExamResult {
  'id' : bigint,
  'completedAt' : bigint,
  'date' : string,
  'score' : bigint,
  'totalQuestions' : bigint,
  'educationLevel' : string,
}
export type ExternalBlob = Uint8Array;
export interface Note {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
}
export interface ProgressData {
  'progressPercentage' : bigint,
  'lastActivityDate' : bigint,
  'totalScore' : bigint,
  'completedActivities' : Array<string>,
  'achievementBadge' : string,
}
export interface Sound {
  'file' : ExternalBlob,
  'category' : SoundCategory,
  'uploadedAt' : bigint,
}
export type SoundCategory = { 'anlaticiBolumGecisi' : null } |
  { 'anlaticiGorevBaslangici' : null } |
  { 'arkaPlanMuzigi' : null } |
  { 'basari' : null } |
  { 'yanlisCevap' : null } |
  { 'anlaticiMotivasyon' : null } |
  { 'secim' : null } |
  { 'anlaticiHataTekrarDene' : null } |
  { 'anlaticiHosgeldiniz' : null } |
  { 'anlaticiBasari' : null } |
  { 'uyari' : null } |
  { 'dogruCevap' : null } |
  { 'gecisSesi' : null };
export interface StudentData {
  'examResults' : Array<ExamResult>,
  'progress' : ProgressData,
  'notes' : Array<Note>,
  'dailyPlans' : Array<DailyPlan>,
  'profile' : StudentProfile,
}
export interface StudentProfile {
  'username' : string,
  'createdAt' : bigint,
  'lastUpdated' : bigint,
  'soundEnabled' : boolean,
  'studentNumber' : string,
  'notificationEnabled' : boolean,
  'avatar' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'canUploadContent' : ActorMethod<[], boolean>,
  'deleteAudio' : ActorMethod<[bigint], undefined>,
  'deleteDailyPlan' : ActorMethod<[string, bigint], undefined>,
  'deleteNote' : ActorMethod<[string, bigint], undefined>,
  'deleteStudentProfile' : ActorMethod<[string], undefined>,
  'getAudioFile' : ActorMethod<[bigint], [] | [AudioFile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [AdminProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyPlans' : ActorMethod<[string], Array<DailyPlan>>,
  'getExamResults' : ActorMethod<[string], Array<ExamResult>>,
  'getNotes' : ActorMethod<[string], Array<Note>>,
  'getProgress' : ActorMethod<[string], [] | [ProgressData]>,
  'getSound' : ActorMethod<[SoundCategory], [] | [Sound]>,
  'getStudentData' : ActorMethod<[string], [] | [StudentData]>,
  'getStudentProfile' : ActorMethod<[string], [] | [StudentProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [AdminProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllAudioFilesWithFiles' : ActorMethod<[], Array<AudioFile>>,
  'listAudioFiles' : ActorMethod<[], AudioFileList>,
  'listSounds' : ActorMethod<[], Array<Sound>>,
  'saveCallerUserProfile' : ActorMethod<[AdminProfile], undefined>,
  'saveDailyPlan' : ActorMethod<[string, DailyPlan], bigint>,
  'saveExamResult' : ActorMethod<[string, ExamResult], bigint>,
  'saveNote' : ActorMethod<[string, Note], bigint>,
  'saveProgress' : ActorMethod<[string, ProgressData], undefined>,
  'saveStudentProfile' : ActorMethod<[StudentProfile], undefined>,
  'syncStudentData' : ActorMethod<[string, StudentData], undefined>,
  'updateDailyPlan' : ActorMethod<[string, bigint, DailyPlan], undefined>,
  'updateNote' : ActorMethod<[string, bigint, Note], undefined>,
  'uploadAudio' : ActorMethod<[string, ExternalBlob], bigint>,
  'uploadSound' : ActorMethod<
    [SoundCategory, { 'url' : string } | { 'file' : ExternalBlob }],
    string
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];