/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AudioFile = IDL.Record({
  'id' : IDL.Nat,
  'audioLabel' : IDL.Text,
  'file' : ExternalBlob,
  'uploadedAt' : IDL.Int,
});
export const AdminProfile = IDL.Record({ 'name' : IDL.Text });
export const DailyPlan = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'activities' : IDL.Vec(IDL.Text),
  'updatedAt' : IDL.Int,
  'goals' : IDL.Vec(IDL.Text),
});
export const ExamResult = IDL.Record({
  'id' : IDL.Nat,
  'completedAt' : IDL.Int,
  'date' : IDL.Text,
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'educationLevel' : IDL.Text,
});
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
});
export const ProgressData = IDL.Record({
  'progressPercentage' : IDL.Nat,
  'lastActivityDate' : IDL.Int,
  'totalScore' : IDL.Nat,
  'completedActivities' : IDL.Vec(IDL.Text),
  'achievementBadge' : IDL.Text,
});
export const SoundCategory = IDL.Variant({
  'anlaticiBolumGecisi' : IDL.Null,
  'anlaticiGorevBaslangici' : IDL.Null,
  'arkaPlanMuzigi' : IDL.Null,
  'basari' : IDL.Null,
  'yanlisCevap' : IDL.Null,
  'anlaticiMotivasyon' : IDL.Null,
  'secim' : IDL.Null,
  'anlaticiHataTekrarDene' : IDL.Null,
  'anlaticiHosgeldiniz' : IDL.Null,
  'anlaticiBasari' : IDL.Null,
  'uyari' : IDL.Null,
  'dogruCevap' : IDL.Null,
  'gecisSesi' : IDL.Null,
});
export const Sound = IDL.Record({
  'file' : ExternalBlob,
  'category' : SoundCategory,
  'uploadedAt' : IDL.Int,
});
export const StudentProfile = IDL.Record({
  'username' : IDL.Text,
  'createdAt' : IDL.Int,
  'lastUpdated' : IDL.Int,
  'soundEnabled' : IDL.Bool,
  'studentNumber' : IDL.Text,
  'notificationEnabled' : IDL.Bool,
  'avatar' : IDL.Text,
});
export const StudentData = IDL.Record({
  'examResults' : IDL.Vec(ExamResult),
  'progress' : ProgressData,
  'notes' : IDL.Vec(Note),
  'dailyPlans' : IDL.Vec(DailyPlan),
  'profile' : StudentProfile,
});
export const AudioFileNoFile = IDL.Record({
  'id' : IDL.Nat,
  'audioLabel' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const AudioFileList = IDL.Record({
  'audioFiles' : IDL.Vec(AudioFileNoFile),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'canUploadContent' : IDL.Func([], [IDL.Bool], ['query']),
  'deleteAudio' : IDL.Func([IDL.Nat], [], []),
  'deleteDailyPlan' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteNote' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteStudentProfile' : IDL.Func([IDL.Text], [], []),
  'getAudioFile' : IDL.Func([IDL.Nat], [IDL.Opt(AudioFile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(AdminProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyPlans' : IDL.Func([IDL.Text], [IDL.Vec(DailyPlan)], ['query']),
  'getExamResults' : IDL.Func([IDL.Text], [IDL.Vec(ExamResult)], ['query']),
  'getNotes' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
  'getProgress' : IDL.Func([IDL.Text], [IDL.Opt(ProgressData)], ['query']),
  'getSound' : IDL.Func([SoundCategory], [IDL.Opt(Sound)], ['query']),
  'getStudentData' : IDL.Func([IDL.Text], [IDL.Opt(StudentData)], ['query']),
  'getStudentProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(StudentProfile)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(AdminProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllAudioFilesWithFiles' : IDL.Func([], [IDL.Vec(AudioFile)], ['query']),
  'listAudioFiles' : IDL.Func([], [AudioFileList], ['query']),
  'listSounds' : IDL.Func([], [IDL.Vec(Sound)], ['query']),
  'saveCallerUserProfile' : IDL.Func([AdminProfile], [], []),
  'saveDailyPlan' : IDL.Func([IDL.Text, DailyPlan], [IDL.Nat], []),
  'saveExamResult' : IDL.Func([IDL.Text, ExamResult], [IDL.Nat], []),
  'saveNote' : IDL.Func([IDL.Text, Note], [IDL.Nat], []),
  'saveProgress' : IDL.Func([IDL.Text, ProgressData], [], []),
  'saveStudentProfile' : IDL.Func([StudentProfile], [], []),
  'syncStudentData' : IDL.Func([IDL.Text, StudentData], [], []),
  'updateDailyPlan' : IDL.Func([IDL.Text, IDL.Nat, DailyPlan], [], []),
  'updateNote' : IDL.Func([IDL.Text, IDL.Nat, Note], [], []),
  'uploadAudio' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Nat], []),
  'uploadSound' : IDL.Func(
      [SoundCategory, IDL.Variant({ 'url' : IDL.Text, 'file' : ExternalBlob })],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AudioFile = IDL.Record({
    'id' : IDL.Nat,
    'audioLabel' : IDL.Text,
    'file' : ExternalBlob,
    'uploadedAt' : IDL.Int,
  });
  const AdminProfile = IDL.Record({ 'name' : IDL.Text });
  const DailyPlan = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'activities' : IDL.Vec(IDL.Text),
    'updatedAt' : IDL.Int,
    'goals' : IDL.Vec(IDL.Text),
  });
  const ExamResult = IDL.Record({
    'id' : IDL.Nat,
    'completedAt' : IDL.Int,
    'date' : IDL.Text,
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'educationLevel' : IDL.Text,
  });
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
  });
  const ProgressData = IDL.Record({
    'progressPercentage' : IDL.Nat,
    'lastActivityDate' : IDL.Int,
    'totalScore' : IDL.Nat,
    'completedActivities' : IDL.Vec(IDL.Text),
    'achievementBadge' : IDL.Text,
  });
  const SoundCategory = IDL.Variant({
    'anlaticiBolumGecisi' : IDL.Null,
    'anlaticiGorevBaslangici' : IDL.Null,
    'arkaPlanMuzigi' : IDL.Null,
    'basari' : IDL.Null,
    'yanlisCevap' : IDL.Null,
    'anlaticiMotivasyon' : IDL.Null,
    'secim' : IDL.Null,
    'anlaticiHataTekrarDene' : IDL.Null,
    'anlaticiHosgeldiniz' : IDL.Null,
    'anlaticiBasari' : IDL.Null,
    'uyari' : IDL.Null,
    'dogruCevap' : IDL.Null,
    'gecisSesi' : IDL.Null,
  });
  const Sound = IDL.Record({
    'file' : ExternalBlob,
    'category' : SoundCategory,
    'uploadedAt' : IDL.Int,
  });
  const StudentProfile = IDL.Record({
    'username' : IDL.Text,
    'createdAt' : IDL.Int,
    'lastUpdated' : IDL.Int,
    'soundEnabled' : IDL.Bool,
    'studentNumber' : IDL.Text,
    'notificationEnabled' : IDL.Bool,
    'avatar' : IDL.Text,
  });
  const StudentData = IDL.Record({
    'examResults' : IDL.Vec(ExamResult),
    'progress' : ProgressData,
    'notes' : IDL.Vec(Note),
    'dailyPlans' : IDL.Vec(DailyPlan),
    'profile' : StudentProfile,
  });
  const AudioFileNoFile = IDL.Record({
    'id' : IDL.Nat,
    'audioLabel' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const AudioFileList = IDL.Record({ 'audioFiles' : IDL.Vec(AudioFileNoFile) });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'canUploadContent' : IDL.Func([], [IDL.Bool], ['query']),
    'deleteAudio' : IDL.Func([IDL.Nat], [], []),
    'deleteDailyPlan' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteNote' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteStudentProfile' : IDL.Func([IDL.Text], [], []),
    'getAudioFile' : IDL.Func([IDL.Nat], [IDL.Opt(AudioFile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(AdminProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyPlans' : IDL.Func([IDL.Text], [IDL.Vec(DailyPlan)], ['query']),
    'getExamResults' : IDL.Func([IDL.Text], [IDL.Vec(ExamResult)], ['query']),
    'getNotes' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
    'getProgress' : IDL.Func([IDL.Text], [IDL.Opt(ProgressData)], ['query']),
    'getSound' : IDL.Func([SoundCategory], [IDL.Opt(Sound)], ['query']),
    'getStudentData' : IDL.Func([IDL.Text], [IDL.Opt(StudentData)], ['query']),
    'getStudentProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(StudentProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(AdminProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllAudioFilesWithFiles' : IDL.Func(
        [],
        [IDL.Vec(AudioFile)],
        ['query'],
      ),
    'listAudioFiles' : IDL.Func([], [AudioFileList], ['query']),
    'listSounds' : IDL.Func([], [IDL.Vec(Sound)], ['query']),
    'saveCallerUserProfile' : IDL.Func([AdminProfile], [], []),
    'saveDailyPlan' : IDL.Func([IDL.Text, DailyPlan], [IDL.Nat], []),
    'saveExamResult' : IDL.Func([IDL.Text, ExamResult], [IDL.Nat], []),
    'saveNote' : IDL.Func([IDL.Text, Note], [IDL.Nat], []),
    'saveProgress' : IDL.Func([IDL.Text, ProgressData], [], []),
    'saveStudentProfile' : IDL.Func([StudentProfile], [], []),
    'syncStudentData' : IDL.Func([IDL.Text, StudentData], [], []),
    'updateDailyPlan' : IDL.Func([IDL.Text, IDL.Nat, DailyPlan], [], []),
    'updateNote' : IDL.Func([IDL.Text, IDL.Nat, Note], [], []),
    'uploadAudio' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Nat], []),
    'uploadSound' : IDL.Func(
        [
          SoundCategory,
          IDL.Variant({ 'url' : IDL.Text, 'file' : ExternalBlob }),
        ],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };